---
title: "Query locations for crews"
author: "steppe"
date: "2023-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message  = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r loab libraries}
library(googleway)
library(tidyverse)
library(sf)
library(tigris)
library(ggrepel)
library(nngeo)
```

```{r}
source('functions.R')
SoS_gkey = Sys.getenv("Sos_gkey")
```


```{r gather all places and their locations}

nvp <- places(state = c('OR', 'NV', 'UT'), cb = T) |>
  dplyr::select(NAME)

counties <- counties(state = 'NV')
```

```{r import vector data of crews areas}

fieldo <- st_read('../../geodata/ADMU/GRT_BASIN/GB_FieldO.shp', quiet = T) %>% 
  mutate(Crew = case_when( 
    Field_Off %in% c('Tonopah', 'Stillwater', 'Caliente') ~ 'SW', 
    Field_Off %in% c('Fillmore', 'Cedar City') ~ 'SE', 
    Field_Off %in% c('Burns Andrews', 'Burns Three Rivers', 'Vale Malheur') ~ 'NW', 
    Field_Off %in% c('Tuscarora', 'Wells', 'Bristlecone') ~ 'NE', 
  ), .before = 'geometry') %>% 
  drop_na(Crew) %>% 
  group_by(Crew) %>% 
  summarize(geometry = st_union(geometry))

fieldo_b <- fieldo %>% 
  st_transform(5070) %>% 
  st_buffer(50000) %>% 
  st_transform(4269) 

nv <- st_join(fieldo_b, nvp, join = st_intersects)
nvp <- filter(nvp, NAME %in% nv$NAME) # reduces false positives from other searches

rm(nv, fieldo, fieldo_b)
```


```{r}
NE <- c('Ely', 'Elko', 'Austin', 'Battle Mountain', 'West Wendover', 
        'Pioche', 'Jackpot', 'Carlin', 'Eureka', 'Wells', 'Lund', 'Baker')
SE <- c('Cedar City', 'Fillmore', 'Caliente', 'Richfield', 'Baker', 'Newcastle', 'St. George')
SW <- c('Tonopah', 'Austin', 'Fallon', 'Amargosa Valley', 'Beatty' , 'Eureka', 'Yerington')
NW <- c('Burns', 'Vale', 'Hiko', 'McDermitt', 'Jordan Valley', 'Denio')
```

```{r gather location data for each field crew, eval = F}

locations <- c(
  'hospital', 'police',  # serious emergency
  'car_repair', 'gas_station', # emergency
  'lodging',  'library'# ReEmergency 
)

ne_areas <- services_fn(locations, dist = 400000,  NE, places_sf = nvp) 
se_areas <- services_fn(locations, dist = 400000,  SE, places_sf = nvp) 
sw_areas <- services_fn(locations, dist = 400000,  SW, places_sf = nvp) 
nw_areas <- services_fn(locations, dist = 400000,  NW, places_sf = nvp) 

```

```{r}
rm(locations, services_fn, within, true_types, coord_grab, SoS_gkey)
```

```{r gather results for the crews and save locally before formatting, eval = F}

ne_areas <- select(ne_areas, -types)
se_areas <- select(se_areas, -types)
sw_areas <- select(sw_areas, -types)
nw_areas <- select(nw_areas, -types)

ifelse(!dir.exists(file.path('../results', 'Google')), 
       dir.create(file.path('../results', 'Google')), FALSE)
st_write(ne_areas, file.path('../results', 'Google', 'NE.shp'), append = F, quiet = T)
st_write(se_areas, file.path('../results', 'Google', 'SE.shp'), append = F, quiet = T)
st_write(sw_areas, file.path('../results', 'Google', 'SW.shp'), append = F, quiet = T)
st_write(nw_areas, file.path('../results', 'Google', 'NW.shp'), append = F, quiet = T)
```

```{r import queries from google}

ne_areas <- st_read(file.path('../results', 'Google', 'NE.shp'), quiet = T)
se_areas <- st_read(file.path('../results', 'Google', 'SE.shp'), quiet = T)
sw_areas <- st_read(file.path('../results', 'Google', 'SW.shp'), quiet = T)
nw_areas <- st_read(file.path('../results', 'Google', 'NW.shp'), quiet = T)

```


```{r assign proper place names to query}
area <- function(x){nvp$NAME[st_nearest_feature(x, nvp)]}

nvp <- st_transform(nvp, st_crs(ne_areas))

ne_areas <- ne_areas %>% mutate(Locality = area(.), .before = 'Service')
se_areas <- se_areas %>% mutate(Locality = area(.), .before = 'Service')
sw_areas <- sw_areas %>% mutate(Locality = area(.), .before = 'Service')
nw_areas <- nw_areas %>% mutate(Locality = area(.), .before = 'Service')

ne_areas <- select(ne_areas, -Localty)
se_areas <- select(se_areas, -Localty)
sw_areas <- select(sw_areas, -Localty)
nw_areas <- select(nw_areas, -Localty)

rm(area)
```

```{r clip records to 10 services per town}

ne_areas <- ne_areas %>% arrange(-usr_rt_) %>% 
  slice_head(n = 10, by = c('Service', 'Locality'))

se_areas <- se_areas %>% arrange(-usr_rt_) %>% 
  slice_head(n = 10, by = c('Service', 'Locality'))

nw_areas <- nw_areas %>% arrange(-usr_rt_) %>% 
  slice_head(n = 10, by = c('Service', 'Locality'))

sw_areas <- sw_areas %>% arrange(-usr_rt_) %>% 
  slice_head(n = 10, by = c('Service', 'Locality'))

```


```{r add distance and direction of location from nearest town}

f_areas_se <- split(se_areas, se_areas$Locality)
f_areas_sw <- split(sw_areas, sw_areas$Locality)
f_areas_ne <- split(ne_areas, ne_areas$Locality)
f_areas_nw <- split(nw_areas, nw_areas$Locality)

ne_areas <- lapply(f_areas_ne, distAZE, places_data = nvp) %>% bind_rows()
se_areas <- lapply(f_areas_se, distAZE, places_data = nvp) %>% bind_rows()
sw_areas <- lapply(f_areas_sw, distAZE, places_data = nvp) %>% bind_rows()
nw_areas <- lapply(f_areas_nw, distAZE, places_data = nvp) %>% bind_rows()

rm(f_areas_se, f_areas_sw, f_areas_ne, f_areas_nw, distAZE)
```


```{r quick map of the field office towns, eval = F}

intermountain_states <- states() %>% 
  filter(NAME %in% c('Nevada', 'Utah', 'Oregon', 'California', 'Idaho', 'Arizona'))

nv_roads <- roads(state = 'NV', county = counties$NAME) %>% 
  filter(RTTYP %in% c('I', 'U', 'C', 'S'))
ca_roads <- roads(state = 'CA', county = c('Inyo', 'Mono', 'Alpine')) %>% 
  filter(RTTYP %in% c('I', 'U', 'C', 'S'))
or_roads <- roads(state = 'OR', county = c('Harney', 'Malheur', 'Lake')) %>% 
  filter(RTTYP %in% c('I', 'U', 'C', 'S'))
id_roads <- roads(state = 'ID', county = c('Owyhee', 'Twin Falls')) %>% 
  filter(RTTYP %in% c('I', 'U', 'C', 'S'))
ut_roads <- roads(
  state = 'UT',
  county = c('Millard', 'Beaver', 'Iron', 'Washington', 'Kane', 'Garfield', 'Piute')) %>% 
  filter(RTTYP %in% c('I', 'U', 'C', 'S'))
roads <- bind_rows(nv_roads, ca_roads, or_roads, id_roads, ut_roads)

rm(nv_roads, ca_roads, or_roads, id_roads, ut_roads)

state_cos <- setNames(
  c('#fdc086', '#beaed4', '#7fc97f', '#ffff99', '#386cb0', '#f0027f'),
  c('Nevada', 'Idaho', 'Oregon', 'Utah', 'California', 'Arizona')
)


bp <- ggplot() +
  geom_sf(data = intermountain_states, aes(fill = NAME), show.legend = F) + 
  geom_sf(data = roads, color = 'grey50') + 
  scale_fill_manual(values = state_cos) +  
  theme_bw()  +
  labs(x = NULL, y = NULL) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(angle = 45, hjust = 0.5, vjust = 0.5),
        plot.title = element_text(hjust = 0.5)) 


# perform the same operation for each crews general area

bbox <- sw_areas %>% 
  st_transform(5070) %>% 
  st_buffer(10000) %>% 
  st_transform(4326) %>% 
  st_bbox()

cc_lab <- nvp %>%  
  st_centroid() %>% 
  st_transform(4326) %>% 
    mutate(longitude = unlist(map(.$geometry,1)),
           latitude = unlist(map(.$geometry,2))) %>% 
  filter(NAME %in% SW)

cc_lab <- cc_lab[st_within(cc_lab, st_as_sfc(bbox)) %>% lengths > 0,]

bp +  
  labs(title = 'SW Crew Area') +
  geom_sf(data = cc_lab) +
  geom_text_repel(data = cc_lab, aes(x = longitude, y = latitude, label = NAME)) + 
  coord_sf(xlim = c(bbox[1], bbox[3]), ylim = c(bbox[2], bbox[4]))
  
ggsave('../results/maps/SW.png', dpi = 150, device = "png")


rm(bbox, cc_lab, bp, state_cos)
```


```{r write out areas information, eval = F}
p <- '../results/spatial'

st_write(ne_areas, file.path(p, 'NE', 'NE.shp'), append = F)
st_write(nw_areas, file.path(p, 'NW', 'NW.shp'), append = F)
st_write(se_areas, file.path(p, 'SE', 'SE.shp'), append = F)
st_write(sw_areas, file.path(p, 'SW', 'SW.shp'), append = F)

rm(nw_areas, ne_areas, sw_areas, se_areas, NE, NW, SE, SW, counties, p, nvp)
```

