---
title: "AIM presences and absences"
author: "steppe"
date: "2023-04-06"
output: html_document
---

```{r}
library(sf)
library(tidyverse)
source('functions.R')

set.seed(28)

p <- '../data'
f <- list.files(p)
```


```{r load in existing presences}

pub_presence <- st_read('../data/SDM-occ/SDM-occ.shp', quiet = T) %>% 
  st_transform(5070)

target_taxa_lkp <- read.csv(file.path(p, f[grep('taxa_2023', f)])) %>% 
  select(species = Species, USDA.Code)

```

```{r load in existing presences 2}

pub_presence <- st_read('../data/SDM-occ/SDM-occ2.shp', quiet = T) %>% 
  st_transform(5070)

target_taxa_lkp <- read.csv(file.path(p, f[grep('taxa_2023', f)])) %>% 
  filter(ELFO == 'X') %>% 
  filter(if_any(c('NE', 'SE', 'SW', 'SE', 'Universal'), ~ str_detect(., 'X', negate = T))) %>% 
  select(species = Species, USDA.Code) 

```

```{r import analytical area for modelling}

p <- '../../geodata'
f <- list.files(p, recursive = T, pattern = 'shp$')

field_off <- st_read(file.path(p, f[grep('GRT', f)]), quiet = T) %>% 
  st_union() %>% 
  st_as_sf() %>% 
  st_transform(5070)

field_off <- nngeo::st_remove_holes(field_off)
field_off <- st_buffer(field_off, dist = 50000)
field_off <- st_convex_hull(field_off)
```

```{r load and subset AIM data}

file.path(p, list.files(p, pattern = 'gdb$', recursive = T))
# for some strange reason this not exactly working! a weird /gdb is being tagged
# onto the end of it... we can manually specify the data beneath
st_layers(dsn = '../../geodata/2021_AIM_Terrestrial/AIMTerrestrial9-1-22.gdb')

AIM_points <- st_read(dsn = '../../geodata/2021_AIM_Terrestrial/AIMTerrestrial9-1-22.gdb', 
        layer = 'TerrADat', quiet = T) %>%
  filter(State %in% c('NV', 'OR', 'CA', 'ID', 'UT')) %>% 
  select(PrimaryKey, geometry = Shape) %>% 
  st_transform(5070) 

AIM_points <- AIM_points[st_covered_by(AIM_points, field_off) %>% lengths > 0,]

spp_richness <- st_read(dsn = '../../geodata/2021_AIM_Terrestrial/AIMTerrestrial9-1-22.gdb', 
        layer = 'tblSpecRichDetail', quiet = T) %>% 
  select(SpeciesList, PrimaryKey) %>% 
  right_join(AIM_points, by = 'PrimaryKey')

```


```{r pull out additional presences from AIM}

spp_found <- inner_join(target_taxa_lkp, spp_richness, 
                        by = c('USDA.Code' = 'SpeciesList')) %>% 
  select(species, PrimaryKey, geometry) %>% 
  st_as_sf()

spp_occurrences <- bind_rows(spp_found, pub_presence) %>% 
  arrange(species) %>% 
  relocate(c('year', 'date'), .before = geometry) %>% 
  mutate(species = str_trim(species)) %>% 
  filter(!species %in% c('Artemisia tridentata',
                         'Elymus elymoides',
                         'Poa secunda'))

# st_write(spp_occurrences, '../data/SDM-occ/SDM-occ.shp', quiet = T, append = F) 
st_write(spp_occurrences, '../data/SDM-occ/SDM-occ2.shp', quiet = T, append = F) 

rm(spp_found, pub_presence, spp_found)
```


```{r determine how many records to come from BLM land}

ensure_multipolygons <- function(X) {
    tmp1 <- tempfile(fileext = ".gpkg")
    tmp2 <- tempfile(fileext = ".gpkg")
    st_write(X, tmp1)
    gdalUtilities::ogr2ogr(tmp1, tmp2, f = "GPKG", nlt = "MULTIPOLYGON")
    Y <- st_read(tmp2)
    st_sf(st_drop_geometry(X), geom = st_geometry(Y))
}

blm <- st_read(dsn = '../../geodata/SMA_WM.gdb', layer = 'SurfaceMgtAgy_BLM', 
               quiet = T) %>% 
  ensure_multipolygons() %>% 
  filter(ADMIN_ST %in% c('CA', 'NV', 'OR', 'ID', 'UT')) %>% 
  select(ADMIN_UNIT_NAME) %>% 
  st_zm(drop = TRUE, what = "ZM") %>% 
  st_cast(to = "MULTIPOLYGON") %>% 
  st_make_valid() %>% 
  st_simplify(dTolerance = 100)

fo <- st_transform(field_off, st_crs(blm))
blm <-  st_intersection(blm, fo)

prop_blm <- round( as.numeric(sum(st_area(blm))) / 
                    as.numeric(st_area(fo)), 2 )

rm(fo)
```


```{r generate absences from AIM plots}

splicies <- split(spp_occurrences, f = spp_occurrences$species)
out <- lapply(splicies, true_absence_ML) %>% 
  bind_rows() %>% 
  st_as_sf()

rm(splicies)
```


```{r Draw random absences}

splicies <- split(out, f = out$species)

field_off <- st_transform(field_off, st_crs(blm))
field_off <- st_erase(field_off, blm)
field_off <- st_transform(field_off, st_crs(out))
field_off <- st_make_valid(field_off)

records <- lapply(splicies, random_draw, polyg = field_off, dist = 5000, 
                  species = species) %>% 
  bind_rows()

rm(out, AIM_points, spp_occurrences, target_taxa_lkp, splicies)
```


```{r}
ifelse(!dir.exists(file.path('../data', 'SDM-pres-abs')), 
       dir.create(file.path('../data', 'SDM-pres-abs')), FALSE)
st_write(records, '../data/SDM-pres-abs/SDM-SDM-pres-abs2.shp', quiet = T, append = F) 
```

```{r}
rm(blm, records, spp_richness, dupe_dropper, Machine_SDM, random_draw, st_erase, 
   true_absence_ML, f, p, prop_blm)
```

